print('Quanto dinheiro?')
print(8*2)
print('Quanto dinheiro você ganharia se lavasse 12 carros e cobrasse R$ 12,50 por cada lavagem?')
print(12 * 12.50)
print('Quantos anos uma pessoa nascida em 2000 terá em 2025?')
print(2025-2000)
print('Variáveis')
print("Em que ano você nasceu?")
nascimento = input()
nascimento= int(nascimento)
print("Em 2025 você terá", 2025- nascimento, "anos!")
print('Desafio: O ano 3000')
print("Em que ano você nasceu?")
nascimento = input()
nascimento= int(nascimento)
print("Em que ano você deseja saber a sua idade?")
x=input()
x=int(x)
print("No ano", x ,"você terá", x- nascimento, "anos!")
print('Desafio: Sua idade de cachorro ')
print("Qual a sua idade?")
nascimento = input()
nascimento= int(nascimento)
print("Se você fosse um cahorro, você teria", nascimento * 7, "anos!")

